### ISSUE TITLE
Example usage is not working correctly

### ISSUE THREAD

**Issue by matthew2564** [bgrnwd/fotmob#352] opened 2022-08-31 15:01 UTC
**Describe the bug**
Using the example provided in the README.md returns a large HTML response (presumably from the error page of the FotMob website)

**To Reproduce**
```
import Fotmob from 'fotmob';
const fotmob = new Fotmob();

fotmob.getMatchesByDate("20201020");
fotmob.getLeague("42", "overview", "league", "America/New_York");
fotmob.getTeam("6017", "overview", "team", "America/New_York");
fotmob.getPlayer("1071179");
fotmob.getMatchDetails("3399269");
```

**Expected behavior**
Expected getPlayer for example to return me a JSON payload.

**Screenshots**
<img width="1787" alt="Screenshot 2022-08-31 at 16 00 23" src="https://user-images.githubusercontent.com/33056264/187711339-fa4fa024-49fd-46c8-9caa-958e3e393082.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1
 - Browser: Brave (Version 1.42.97  Chromium: 104.0.5112.102 (Official Build)  (x86_64))

**Comment by bgrnwd** [comment] 2022-09-02 06:10
Thanks for reporting this, I'll do some more investigation over the weekend. On first glance, it seems like this may be an API change.

**Comment by bgrnwd** [comment] 2022-09-14 00:49
Confirmed it's an API change. I should be able to publish a version with the fix in the next couple days.

**Comment by bgrnwd** [comment] 2022-09-16 01:17
@matthew2564 Give `1.0.4` a try and let me know if that fixes it

**Comment by matthew2564** [comment] 2022-09-22 07:00
@bgrnwd Bumped version to 1.0.4. Seem to have encountered s second issue.

Updated the example usage, and implemented the following code...
<img width="500" alt="Screenshot 2022-09-22 at 07 49 13" src="https://user-images.githubusercontent.com/33056264/191677639-2d0d0492-9d9f-444c-b6be-dd4b2205dc20.png">

This is the output when executing the above code
<img width="371" alt="Screenshot 2022-09-22 at 07 50 22" src="https://user-images.githubusercontent.com/33056264/191677932-d59e619c-d71d-4dc3-b6c4-2d487980f48f.png">

The README.md suggests the methods should return a value, but upon running the code and looking at the type definitions, the methods return void.

<img width="609" alt="Screenshot 2022-09-22 at 07 58 07" src="https://user-images.githubusercontent.com/33056264/191679367-89f4d2df-c4ef-4a4f-b8ad-d80ad5b62f76.png">

Any help is appreciated, thanks!

**Comment by bgrnwd** [comment] 2022-10-01 02:30
@matthew2564 Hmm, the methods should return a value. Full disclosure, I'm not a JS/TS dev so I'm learning as I go. I'll see if I can figure out why. I did notice the type definition file is empty now too.

I've been meaning to switch to a logger instead of printing to the console so the URL, `undefined` and `false` will go away eventually.

**Comment by olamarvel** [comment] 2022-12-16 14:54
i think this is due to the compiler you used if yoou checked the compiled code in dist/fotmob.js u will see that each fucntion is being called in a self involking function with does not allow for returned values

**Comment by olamarvel** [comment] 2022-12-16 14:54
would send screenshot soon

**Comment by bgrnwd** [comment] 2023-07-10 01:53
@olamarvel Thanks for the info and PR. I made the changes you suggested in #404 

@matthew2564 Give `1.1.0` a try, I _think_ I've got the example usage working this time

**Comment by bgrnwd** [comment] 2024-01-09 02:49
@matthew2564 Want to give this a try again? There's been a couple new versions since July

**Comment by ItamarShDev** [comment] 2024-01-24 18:59
@bgrnwd maybe we should close it

**Comment by bgrnwd** [comment] 2024-02-03 02:48
@matthew2564 Going to close this but happy to re-open it if you're still having the same issue with the newer versions.

**Closed by bgrnwd** 2024-02-03 02:48 UTC
Labels: bug
